### ISSUE TITLE
The paper name is...

### ISSUE THREAD

**Issue by LeoNatan** [Nicejinux/NXDrawKit#1]
"Canvas": https://en.wikipedia.org/wiki/Canvas

What you call "canvas" is actually an "easel": https://en.wikipedia.org/wiki/Easel

Cool project!

**Comment by Nicejinux** [comment]
Wow Thanks.
But, what I meant is the cloth on the canvas.
I know what the easel is.
Anyway Thanks a lot!!

**Comment by LeoNatan** [comment]
The canvas is the cloth/paper.

**Comment by Nicejinux** [comment]
Ah.. ok..
so you mean, Paper -> Canvas right?
and Canvas -> Easel ??
Easel is too far from what I expected.. haha.

How about Canvas -> Frame?
Is it make sense?

**Comment by LeoNatan** [comment]
Yeah, that also works. 

You could also keep canvas as canvas, and rename the "paper" as "drawing", as that is what it signifies.

**Comment by Nicejinux** [comment]
Oh.. that's good..
Thanks.
I'll update soon.

**Comment by Nicejinux** [comment]
NXDrawKit is updated and what your suggestions are applied.
Thanks @LeoNatan
