### ISSUE TITLE
Undo clears background image

### ISSUE THREAD

**Issue by waltermvp** [Nicejinux/NXDrawKit#10]
When creating a `Canvas` with a background image with `Canvas(backgroundImage: UIImage.init(named: "Image")!)` calling undo wipes everything including the background image.

The undo functionality should undo the first drawing but not clear the background image. It seems the first drawing and the setting of the image are merged into the first action.

**Comment by waltermvp** [comment]
Also is there  way to clear all the `undos`?

**Comment by Nicejinux** [comment]
Oh.. I see.
I'll fix it.
and I'll check `clear undo` 

Thanks.

**Comment by waltermvp** [comment]
@Nicejinux thanks for the quick response.

**Comment by waltermvp** [comment]
Any estimate till when it's fixed? Id be happy to submit a PR if it helps :)

**Comment by Nicejinux** [comment]
Oh. sure. You can submit PR anytime~~

**Comment by waltermvp** [comment]
@Nicejinux great ill try to see if i can get it done tonight

**Comment by Nicejinux** [comment]
Fixed.
Please update and check.

Thanks.

**Comment by waltermvp** [comment]
@Nicejinux works perfectly :) thanks !!
