### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by Raymond26** [Nicejinux/NXDrawKit#12]
Any plans for a Swift 3 release?

**Comment by Nicejinux** [comment]
Of course I have.
As you know, NXDrawKit is using SnapKit for autolayout.
SnapKit doesn't fully support Swift3.0 yet.
so I'm looking for the way the SnapKit 3.0 integration. 

I want to support Swift 3.0 ASAP.

Thanks.

**Comment by Nicejinux** [comment]
I'm working on it without SnapKit.
NXDrawKit could be released for Swift 3.0 in this weekend.

Thanks.

**Comment by Nicejinux** [comment]
Done.
