### ISSUE TITLE
Pod error

### ISSUE THREAD

**Issue by MartijnSchoemaker** [Nicejinux/NXDrawKit#13]
- `NXDrawKit (~> 0.5.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `NXDrawKit (~> 0.5.0)`.

**Comment by Nicejinux** [comment]
Oh.. I'll check.

**Comment by Nicejinux** [comment]
NXDrawKit 0.5.0 doesn't need any dependency.
I can't understand what you are saying.

Can you explain more about the dependency?

If you want to use this with Pod, just add that line on the Podfile.
pod 'NXDrawKit', '~> 0.5.0'

Thanks.

**Comment by MartijnSchoemaker** [comment]
That's what I do, but it gives me the error in my first post. When I use it without specific version 0.5.0 it works fine but then I get version 0.4.1.

Podfile:
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'DrawingTest' do
    pod 'NXDrawKit', '~> 0.5.0'
end

Pod install:
Analyzing dependencies
[!] Unable to satisfy the following requirements:
- `NXDrawKit (~> 0.5.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `NXDrawKit (~> 0.5.0)`.

You have either:
- out-of-date source repos which you can update with `pod repo update`.
- mistyped the name or version.
- not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by Nicejinux** [comment]
Oh.. I see. I'll check and let you know.
Thanks for reporting.

**Comment by Nicejinux** [comment]
I checked.
You need to update a pod 1.1.0 or higher.

you can update with this command.
`sudo gem install cocoapods --pre`

can you update and check it again?

**Comment by MartijnSchoemaker** [comment]
I already did this, but tried it again.
Same result. 

$ pod --version
1.1.0.rc.3

**Comment by Nicejinux** [comment]
Oh. I'll check more.

**Comment by Nicejinux** [comment]
Hi. Did you find something?
I didn't get anything for this. I could make that error anymore.

I think it's pod problem. can you check at Cocoapods?

**Comment by Nicejinux** [comment]
I'll close this issue.
let me know how it is going
