### ISSUE TITLE
any ideas how to draw svg by ink datas?

### ISSUE THREAD

**Issue by longxianlin** [Nicejinux/NXDrawKit#15]
I have ink datas, generated by google input tools. 
like this
```
[[[582,582,582,581,581,580],
            [273,274,275,275,276,276],
            [0,529,537,554,569,1009]]]
```
they are x offset,y offset, time intervals
how to changed them to a png in canvas?
any idea

**Comment by Nicejinux** [comment]
Sorry for late reply.
I moved to the other company recently.

what's that values?
can you explain each value?

I think NXDrawKit can't draw svg data.
because, NXDrawKit is fixed size canvas.

If you explain in detail, I'll check more about that.
Thanks.
