### ISSUE TITLE
Carthage Error

### ISSUE THREAD

**Issue by vasiliilevkovskii** [Nicejinux/NXDrawKit#19]
*** No Cartfile.resolved found, updating dependencies
*** Fetching NXDrawKit
*** Checking out NXDrawKit at "0.5.0"
*** xcodebuild output can be found in /var/folders/_c/3gsl_2314yb_xbhnhc1ld89h0000gn/T/carthage-xcodebuild.MndZdz.log
Dependency "NXDrawKit" has no shared framework schemes

cart file
`github "nicejinux/NXDrawKit" ~> 0.5.0`

carthage version
0.20.0

xcode
8.2.1

**Comment by Nicejinux** [comment]
sorry. I'll fix it and let you know.

Thanks.

**Comment by bshyong** [comment]
Same issue for me... any idea how to fix this?

**Comment by Nicejinux** [comment]
@bshyong 
Sorry. I don't know how to fix it, but I found this comment from GitHub.
can you check this first?

https://github.com/Carthage/Carthage/issues/1890

**Comment by IcaroBritto** [comment]
I think that carthage requires a configured xcodeproj file. Something like [this](https://github.com/Alamofire/Alamofire/tree/master/Alamofire.xcodeproj/xcshareddata/xcschemes).

See [this](https://stackoverflow.com/questions/35054788/carthage-no-shared-framework-schemes-for-ios-platform-for-my-own-framework) post on StackOverflow.
