### ISSUE TITLE
Bug found with solution

### ISSUE THREAD

**Issue by Horse888** [Nicejinux/NXDrawKit#20]
Palette.swift

Line 200: 
`self.delegate?.didChangeBrushWidth?(self.brush.alpha) `
should be 
`self.delegate?.didChangeBrushWidth?(self.brush.width)`

**Comment by Nicejinux** [comment]
WOW
Thank you so much!!

**Comment by Nicejinux** [comment]
Fixed. 
Thanks @ZuYuanZhou
