### ISSUE TITLE
Xcode 9 and Swift 4 support

### ISSUE THREAD

**Issue by valeriologiudice** [Nicejinux/NXDrawKit#22]
Will a new update for Xcode 9 and Swift 4 ever come? This is a great library, deserves to be updated.

**Comment by Nicejinux** [comment]
sure. I'm updating a framework currently.
It will be released soon.
@valeriologiudice Thanks for concerning about NXDrawKit.

**Comment by Nicejinux** [comment]
updated.
If you have a problem for using NXDrawKit on Swift4, let me know anytime.

Thanks.

**Comment by valeriologiudice** [comment]
@Nicejinux thank you my friend, everything work well! I will keep testing and I'll eventually tell you if I'll find any problem. Best.
