### ISSUE TITLE
Change 

### ISSUE THREAD

**Issue by Jkurbs** [Nicejinux/NXDrawKit#23]
Hi, I'm getting this error 
<img width="728" alt="screen shot 2017-10-10 at 9 05 29 pm" src="https://user-images.githubusercontent.com/10508898/31417638-e47561fe-adfe-11e7-9091-1a5cb6bd990b.png">

unexpectedly found nil while unwrapping an Optional value
(lldb) 

Can you help me? Thank you!

**Comment by Nicejinux** [comment]
Hi @Jkurbs 

Can you explain more about that error?

Did you change example code?
If yes, let me know what part is changed.

If no, when did you get that error? 
Run this example and get that error right away? or
Run and draw something and then get that error? 

Thanks.
