### ISSUE TITLE
add smileys or sticker feature

### ISSUE THREAD

**Issue by muni510** [Nicejinux/NXDrawKit#27]
Hi Nicejinux,

Very nice library from you.
I need some help as follows:
How can we add smileys or stickers on canvas view ???

Thanks in advance

**Comment by Nicejinux** [comment]
Hi. 
Sorry for late reply. I was incredibly busy last week.

It's depends on what kind of image you want to add.

The easiest way is adding UIImageView.
and If you want to move the position of the sticker by finger,
add gesture recognizer on the UIImageView.

or, Can you explain more about what you thought?
if it's not that hard to implement, I'll add that feature.

Thanks.

**Comment by muni510** [comment]
Thank you for a reply.
doing the same as you have suggested If I having any issue in implementing it. 
I will ask for your help.

Thank you

**Comment by muni510** [comment]
Hi Nicejinux,
hopes your doing well.

I have added a smiley feature, here needs some help for update sessions so we can undo-redo the drag & drop, resize and rotate features.

Thank you
