### ISSUE TITLE
Change Brush Width and Color default

### ISSUE THREAD

**Issue by walkerdev777** [Nicejinux/NXDrawKit#30]
Hi,

Need to adjust Brush Width the thinnest the thinnest line, also the color clear by default

Thanks

**Comment by Nicejinux** [comment]
Hi. @walkerdev777 Sorry for late reply.
Recently, I was incredibly busy.
Anyway,

If you want to change Brush width, you should implement method below and return width you want.
``` swift
func widthWithTag(tag: NSInteger) -> CGFloat
``` 
  
  
And, If you implement method below and return clear color, you can use clear color.
``` swift
func colorWithTag(tag: NSInteger) -> UIColor?
``` 

Is this correct answer you want?

if not, let me know detailedly

Thanks.
