### ISSUE TITLE
Update to Swift 5

### ISSUE THREAD

**Issue by jessemx109** [Nicejinux/NXDrawKit#32]
can you please upgrade this library to swift 5

**Comment by Nicejinux** [comment]
I’ll do it this weekend.

**Comment by Nicejinux** [comment]
> can you please upgrade this library to swift 5

0.8.0 is released
Can you test it?

**Comment by jessemx109** [comment]
I'll upgrade today and test. 
Thanks for the quick turn around

**Comment by jessemx109** [comment]
Just upgraded and everything looks good. We are using basic functionality from the framework but the new version compiles fine and is working for our needs
