### ISSUE TITLE
Create a file/data format 

### ISSUE THREAD

**Issue by akac** [Nicejinux/NXDrawKit#4]
Create a syncable, savable file format that apps can use to interchange with. 

Support copy/paste as image or as the encoded data between apps

**Comment by Nicejinux** [comment]
Oh. Ok I'll try. 
Thanks.

**Comment by Nicejinux** [comment]
Can I ask you something?
What you want is sharing with UIActivityViewController right?

**Comment by Nicejinux** [comment]
I updated an example code for image sharing.
If it's not what you wanted, let me know.

Thanks.
