### ISSUE TITLE
Does it handle Auto-Rotate

### ISSUE THREAD

**Issue by olbrichj** [Nicejinux/NXDrawKit#6]
I'm looking into a lot of drawing kits and haven't found a single one yet, that handles auto-rotation. 
Would be amazing to see this working. Either by refitting it onto the screen, or just drawing it as if the view didn't rotate.

**Comment by leviathan** [comment]
@olbrichj I don't understand what you're referring to as "auto-rotate".
Do you mean device rotation or rotation of the view ?
Could you describe you desired use case more detailed?

**Comment by olbrichj** [comment]
yes I'm referring to device rotation.
I did write a video app, in which you could do annotation on top of the video. Rotating the device was the main issue with all the libraries I've found.

**Comment by Nicejinux** [comment]
Thanks @leviathan. That's what I'm going to ask.
@olbrichj If you want to use "Auto-rotate", you have to implement in your source code.
I can add "Auto-rotate" into my example, but I don't know whether it can help you or not.
All my components are just a view, so I can add "auto-rotate" easily.
but your's is video. I don't know about video apps.

**Comment by Nicejinux** [comment]
I'll close this issue.
If you want me to implement that feature into my example code,
add a comment here.
Thanks.
