### ISSUE TITLE
Snapkit version

### ISSUE THREAD

**Issue by andrewSvsg** [Nicejinux/NXDrawKit#9]
Hi
Now you use in SnapKit with version < 0.2 
last SnapKit version is '0.22.0'
Could you please update pod to last SnapKit?

Thanks
Great work

**Comment by Nicejinux** [comment]
Oh sure.
I'm on summer vacation now.
I'll update by this week.
Thanks.

**Comment by Nicejinux** [comment]
Updated.
Thanks.

**Comment by chapayGhub** [comment]
Thanks!
